Helidon v2.1.0
oracle/oci-react-samples pull request #36
Opened 2024-09-06 12:53 UTC by aberinnj

- Dependencies still using JDBC v19 and other packages that may be uneccessary, **Updated**
- No NPE guards for missing environment variables, **Updated**
- Environment variables not homogenous, and undocumented, **Updated**
- Add README for running instructions, **Updated**
- Improve code to be more flexible, **Updated**

2024-09-06 12:58 UTC, aberinnj commented
@Kuassim Please review when possible and merge

2024-09-06 16:38 UTC, Kuassim commented on mtdrworkshop/backend/src/main/java/com/oracle/database/AppDatasource.java
> +package com.oracle.database;
Can you please add the Oracle Copyrights

2024-09-06 16:40 UTC, Kuassim commented on mtdrworkshop/backend/src/main/java/com/oracle/database/AppDatasource.java
> +    private static AppDatasource instance = null;
It looks like you have 3 spaces instead of 2; not a big deal as long as it is not a tab.

2024-09-06 16:48 UTC, Kuassim requested changes
1. One Java code does not have Copyright (unless I am not seeing right).
2. Make sure to use 2 tabs for indentation at each level (it looks like you are using 3 and sometimes more than 3.
3. Use try-with-resource for code blocks with statements and resultSets; to  make sure these are closed/freed.

2024-09-06 18:06 UTC, aberinnj commented
@Kuassim 
1. fixed
2. fixed I hope! Some code are using builder methods so they may be indented more
3. I do not see any files having this signature

2024-09-06 18:14 UTC, Kuassim approved these changes

2024-09-06 18:43 UTC, aberinnj commented
@jeandelavarene Please review and merge when possible

2024-09-10 09:02 UTC, jeandelavarene approved these changes

2024-09-10 09:02 UTC, merged